/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 cube.gltf 
Author: DoobiDooba (https://sketchfab.com/DoobiDooba)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rubiks-cube-155420e09a124ec3a3bcca0852280672
Title: rubik's cube
*/

import { useGLTF } from '@react-three/drei'
import { useBox } from '@react-three/cannon'


export default function Model({ position, ...props }) {
  const { nodes, materials } = useGLTF('/assets/3D-models/rubiks_cube/cube.gltf')
  
  const [ref] = useBox(() => ({
    type: 'Dynamic',
    mass: 5,
    position: position || [0, 0, 0],
    args: [1.9, 1.9, 1.9],
    material: {
      friction: 0.7,
      restitution: 0.7,
    },
    linearDamping: 0.7,
    angularDamping: 0.7,
  }))

  return (
    <group ref={ref} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1.154}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.RubixCube_RubixCube_0.geometry} material={materials.RubixCube} rotation={[-Math.PI / 2, 0, 0]} scale={1500} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('//assets/3D-models/rubiks_cube/cube.gltf')
